<!-- sidebar -->
<?= $this->sidebar->getSidebarByName('demo') ?>

<!-- main -->
<main class="flex-grow-1 overflow-auto p-2"></main>

<!-- id__opus-demo-static-modal -->
<?= $this->staticModal->getModalByName("opus-demo-static-modal") ?>

<!-- id__opus-demo-dynamic-modal -->
<?= $this->dynamicModal->getModalByName("opus-demo-dynamic-modal") ?>

<!-- id__opus-demo-bonuses-table-edit-modal -->
<?= $this->demoBonusesTableEdit->getModalByName("opus-demo-bonuses-table-edit-modal") ?>

<!-- TableEventView if exists -->
<?= (isset($this->dtEvent)) ? $this->dtEvent : null; ?>
