<?php

/**
 * @Project: Opus
 * @Version: 1.0
 * @Author: Tomasz Ułazowski
 * @Date:   2026-05-19 16:48:09
 * @Last Modified by:   Tomasz Ułazowski
 * @Last Modified time: 2026-05-19 20:26:58
 **/

namespace Opus\controller\event;

use stdClass;
use Opus\config\Config;
use Opus\controller\request\Request;
use Opus\controller\exception\ControllerException;

/**
 * Handles HTML content injection for asynchronous events
 *
 * This class provides functionality to:
 * - Load and validate configuration for HTML injection events
 * - Include specified PHP files and capture their output
 * - Return the captured HTML content as JSON responses
 *
 * The class uses output buffering to capture HTML generated by included files
 * and serves it as part of AJAX responses.
 *
 * @example
 * index.php?api=injectevent&app=skeleton&event=hello
 */
class InjectEventHtml
{
	private static object $config;
	private static ?string $indexInjectHtml = null;

	/**
	 * Selects and validates configuration for the event injection
	 *
	 * This method:
	 * 1. Retrieves app and event parameters from the URL
	 * 2. Loads the corresponding configuration
	 * 3. Validates that the file parameter exists and points to a valid file
	 *
	 * @return void
	 * @throws ControllerException If configuration is invalid or file doesn't exist
	 */
	private static function selectConfig(): void
	{
		self::$config = new stdClass();
		self::$config->app = Request::fromUrl('app');
		self::$config->event = Request::fromUrl('event');
		self::$config->inject = Config::getConfig(self::$config->app)->injectEvent->{self::$config->event};
		self::$config->inject->file ??= false;

		// Validate file parameter exists in configuration
		if (self::$config->inject->file === false) {
			throw new ControllerException(
				'controller\injectEvent\validateConfig\param',
				[
					'message' => ['file', self::$config->inject->file],
					'details' => [self::$config->app, self::$config->event]
				],
				ControllerException::TYPE_API_EXCEPTION
			);
		}

		// Validate file exists on filesystem
		file_exists(self::$config->inject->file)
			?: throw new ControllerException(
				'controller\injectEvent\validateConfig\file',
				['message' => self::$config->inject->file],
				ControllerException::TYPE_API_EXCEPTION
			);
	}

	/**
	 * Processes and outputs HTML injection event
	 *
	 * This method:
	 * 1. Validates the configuration
	 * 2. Includes the specified file and captures its output
	 * 3. Returns the captured HTML as a JSON response
	 *
	 * @return void
	 * @throws ControllerException If configuration validation fails
	 */
	public static function doInjectEvent(): void
	{
		self::selectConfig();

		// Capture output from the included file
		ob_start();
		require_once self::$config->inject->file;
		self::$indexInjectHtml = ob_get_clean();

		// Return JSON response with captured HTML
		echo json_encode([
			'success' => true,
			'index' => self::$indexInjectHtml
		]);
	}
}
