<!-- main -->
<main class="flex-grow-1 overflow-auto p-2">
	<div class="container">
		<div class="row">
			<div class="col">
				<?= $this->table->getTableById('id_settings-users-dt') ?>
			</div>
		</div>
	</div>
</main>

<!-- id__opus-settings-groups -->
<?= $this->modals->groups->getModalByName("opus-settings-groups") ?>

<!-- id__opus-settings-reset-password-by-admin -->
<?= $this->modals->reset->getModalByName("opus-settings-reset-password-by-admin") ?>

<!-- TableEventView if exists -->
<?= (isset($this->dtEvent)) ? $this->dtEvent : null; ?>
